# Generated by Django 4.0.3 on 2022-04-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_apply_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
